version: '3.8'

services:
  mongodb:
    image: mongo:latest
    restart: always
    expose:
      - "27017"
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=adminpassword
    networks:
      - web

  mongo_express:
    image: mongo-express:latest
    restart: always
    expose:
      - "8081" 
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=adminpassword
      - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
      - mongodb
    networks:
      - web

  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - web

  beergame_backend:
    build:
      context: ./beergame_backend
      dockerfile: Dockerfile
    volumes:
      - ./beergame_backend:/app
    expose:
      - "8000"
    environment:
      - PORT=8000
      - MONGODB_URL=mongodb://admin:adminpassword@mongodb:27017/
      - MONGODB_DB=beergame
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - mongodb
    networks:
      - web

  beergame_frontend:
    build:
      context: ./beergame_frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./beergame_frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=/api
    depends_on:
      - beergame_backend
    networks:
      - web

  msgames_docs:
    build:
      context: ./msgames_docs
      dockerfile: Dockerfile
    ports:
      - "3002:80"
    networks:
      - web

  survey_backend:
    build:
      context: ./survey_backend
      dockerfile: Dockerfile
    volumes:
      - ./survey_backend:/app
    expose:
      - "8001"
    environment:
      - PORT=8001
      - MONGODB_URL=mongodb://admin:adminpassword@mongodb:27017/
      - MONGODB_DB=survey
    command: uvicorn app:app --host 0.0.0.0 --port 8001 --reload
    depends_on:
      - mongodb
    networks:
      - web

  survey_frontend:
    build:
      context: ./survey_frontend
      dockerfile: Dockerfile
    expose:
      - "80"
    depends_on:
      - survey_backend
    networks:
      - web
    volumes:
      - ./survey_frontend/nginx.conf:/etc/nginx/conf.d/default.conf

networks:
  web:
    driver: bridge

volumes:
  mongodb_data:
    name: msgames_mongodb_data
    external: true
  mongodb_config:
    name: msgames_mongodb_config
    external: true
  caddy_data:
  caddy_config: